-- ORDENAR EL RESULTADO DE LA CONSULTA

	-- ORDER BY numero de campo
		SELECT * FROM persons ORDER BY 3;	 -- ORDENA POR ORDEN SEGUN LA COLUMNA 2 (last_name)
        SELECT * FROM persons ORDER BY 2 DESC;	 -- ORDENA LO MISMO PERO DESCENDENTE 
        SELECT * FROM persons ORDER BY 2 DESC, 4 DESC;	 -- LO MISMO PERO SI HAY IGUALDAD QUE MUESTRE EL + RECIENTE
        
	-- ORDER BY nombre de campo	
		SELECT * FROM persons ORDER BY created_at; 	-- OREDENA SEGUN EL CAMPO LLAMADO created_at
